<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_11_PDT_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_11_PDT_2018.jpg><img src=Sat_Aug_11_14_52_11_PDT_2018.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_16_PDT_2018.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_16_PDT_2018.jpg><img src=Sat_Aug_11_14_52_16_PDT_2018.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="9026" started-at="2018-08-11T21:52:07Z" finished-at="2018-08-11T21:52:16Z">
    <groups>
    </groups>
    <test name="Login  Test" duration-ms="4145" started-at="2018-08-11T21:52:07Z" finished-at="2018-08-11T21:52:12Z">
      <class name="comw2a.testcases.LoginTest">
        <test-method status="FAIL" signature="LoginTest(java.util.Hashtable)[pri:0, instance:comw2a.testcases.LoginTest@7516e4e5]" name="LoginTest" duration-ms="2300" started-at="2018-08-11T21:52:07Z" data-provider="dp" finished-at="2018-08-11T21:52:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=mudeza123, runmode=Y, username=portnovtest+1@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed
at org.testng.Assert.fail(Assert.java:96)
at comw2a.testcases.LoginTest.LoginTest(LoginTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_11_PDT_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_11_PDT_2018.jpg><img src=Sat_Aug_11_14_52_11_PDT_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginTest -->
      </class> <!-- comw2a.testcases.LoginTest -->
    </test> <!-- Login  Test -->
    <test name="Create Account Test" duration-ms="4871" started-at="2018-08-11T21:52:12Z" finished-at="2018-08-11T21:52:16Z">
      <class name="comw2a.testcases.LoginTest">
        <test-method status="PASS" signature="tearDown()[pri:0, instance:comw2a.testcases.LoginTest@7516e4e5]" name="tearDown" is-config="true" duration-ms="638" started-at="2018-08-11T21:52:16Z" finished-at="2018-08-11T21:52:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- comw2a.testcases.LoginTest -->
      <class name="comw2a.testcases.CreateAccountTest">
        <test-method status="FAIL" signature="createAccountTest(java.util.Hashtable)[pri:0, instance:comw2a.testcases.CreateAccountTest@21baa903]" name="createAccountTest" duration-ms="4521" started-at="2018-08-11T21:52:12Z" data-provider="dp" finished-at="2018-08-11T21:52:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{accountname=Raman}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed
at org.testng.Assert.fail(Assert.java:96)
at comw2a.testcases.CreateAccountTest.createAccountTest(CreateAccountTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_16_PDT_2018.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Sat_Aug_11_14_52_16_PDT_2018.jpg><img src=Sat_Aug_11_14_52_16_PDT_2018.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
      </class> <!-- comw2a.testcases.CreateAccountTest -->
    </test> <!-- Create Account Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
